package by.http.autopark.controller;

/**
 * in this enumeration we describe all possible commands for the controller
 */

public enum CmdEnum {
    MESSAGE_SUCCESS_REGISTRATION("MESSAGE_SUCCESS_REGISTRATION"),
    GO_TO_REGISTRATION("GO_TO_REGISTRATION"),
    REGISTRATION("REGISTRATION"),
    GO_TO_SIGN_IN("GO_TO_SIGN_IN"),
    GO_TO_MAIN_MENU("GO_TO_MAIN_MENU"),
    USER_SIGN_IN("USER_SIGN_IN"),
    SHOW_ALL_ORDERS("SHOW_ALL_ORDERS"),
    GO_TO_ADD_ORDER_PAGE("GO_TO_ADD_ORDER_PAGE"),
    ORDER_REGISTRATION("ORDER_REGISTRATION"),
    GO_TO_DELETE_ORDERS_PAGE("GO_TO_DELETE_ORDERS_PAGE"),
    GO_TO_ADD_CAR_PAGE("GO_TO_ADD_CAR_PAGE"),
    CAR_REGISTRATION("CAR_REGISTRATION"),
    GO_TO_DELETE_CAR("GO_TO_DELETE_CAR"),
    SHOW_ALL_CARS("SHOW_ALL_CARS"),
    CHANGE_AVAILABILITY("CHANGE_AVAILABILITY"),
    CHANGE_AVAILABILITY_CAR("CHANGE_AVAILABILITY_CAR"),
    GO_APPROVE_CERTAIN_ORDER("GO_APPROVE_CERTAIN_ORDER"),
    GO_TO_DELETE_ORDER("GO_TO_DELETE_ORDER"),
    GO_TO_APPROVE_ORDERS("GO_TO_APPROVE_ORDERS"),
    GO_TO_ADD_APPROVED_ORDER("GO_TO_ADD_APPROVED_ORDER"),
    SHOW_ALL_DRIVERS_ORDERS("SHOW_ALL_DRIVER'S_ORDERS"),
    CHANGE_STATUS_BY_DRIVER("CHANGE_STATUS_BY_DRIVER"),
    CHANGE_LANGUAGE("CHANGE_LANGUAGE");


    private String command;
      CmdEnum(String enumCommand){
         command=enumCommand;
     }
     public String getCommand(){
         return   command;
     }


}
